Convert GuessControl and NumberGussingGame class to functional component
Code-the-Dream-School/ctd-react-numberGuessingAssignment pull request #22
Opened 2023-06-05 17:21 UTC by JafariM

2023-06-08 01:26 UTC, XeniyaDob commented on src/GuessControl.js
> +class GuessControlOld extends Component {
Great, you created a functional component. You can delete this class component.

2023-06-08 01:35 UTC, XeniyaDob commented on src/GuessControl.js
>  import React, { Component } from "react";
You can delete everything related to the class component

2023-06-08 01:38 UTC, XeniyaDob requested changes
Great job! I added a couple of comments. One important thing, you need to push your changes to your main branch, not CTD main.

2023-06-13 06:08 UTC, JafariM commented
Thank you for your review, I will fixed the issues

2024-11-04 21:43 UTC, closed without merging